title: Konstructs
email: contact@konstructs.org
url: https://www.konstracts.org
description: An open source Infiniminer/Minecraft inspired multiplayer game

color:
  primary-dark: '#000000'
  links: '#219ab3'

markdown: kramdown
permalink: /:title/
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
    - Dockerfile
    - Makefile

