title: Konstructs
description: An open source Infiniminer/Minecraft inspired multiplayer game
markdown: redcarpet
highlighter: pygments
permalink: /:title/
navigation:
  - name: Home
    url: /
  - name: Download
    url: /download/
  - name: News
    url: /news/
  - name: About
    url: /about/
  - name: GitHub
    url: "http://github.com/konstructs"
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
    - Dockerfile
    - Makefile
