title: Konstructs
description: An open source Infiniminer/Minecraft inspired multiplayer game
markdown: redcarpet
highlighter: pygments
permalink: /:title/
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
